### ISSUE TITLE
Icon Bug

### ISSUE THREAD

**Issue by ghost** [a2/touch-baer#1]
The first icon shown it's a spray can instead of the bear photo, see image. The correct icon only shows after clicking the spray can. Additionally right after pressing on the spray can many controller actions are displayed such as pause, stop, etc.
<img width="1116" alt="bug3" src="https://cloud.githubusercontent.com/assets/393764/24310109/fb495946-10a4-11e7-9b59-d27f9aa5082f.png">
<img width="1116" alt="bug-1" src="https://cloud.githubusercontent.com/assets/393764/24309944/450cd090-10a4-11e7-82b2-9cc6988aa110.png">

**Comment by a2** [comment]
@luisthedude, the "spray can" icon is an Xcode-supplied toolbar providing additional debugging controls.

**Comment by ghost** [comment]
So just to clarify this will not be shown once you build the app correct?

**Comment by a2** [comment]
This is correct. You can build and run the app without debugging to verify this.

**Comment by ghost** [comment]
@a2 Can confirm you were correct; however, the icon doesn't stay active after the initial tap.

**Comment by a2** [comment]
@luisthedude Can you clarify what you mean by "the icon doesn't stay active"?

**Comment by ghost** [comment]
@a2 Sure thing please see the following video, it should explained what I mean: https://sendvid.com/23zuqq8m, compare to this: https://sendvid.com/unny1nt2.

**Comment by a2** [comment]
This is by design.
