### ISSUE TITLE
Swift Version

### ISSUE THREAD

**Issue by L1cardo** [a2/touch-baer#5]
Hi !
I am a student who is learning programming just now. I am working on my own little project ,and found that touch-baer is a great tool that can help me to put my icon on touchbar.
Unfortunately , I am learning swift and blind to OC, can you write a swift version of this ? 
Thanks!!

**Comment by a2** [comment]
Hi @L1cardo, unfortunately the ability to forward declare undocumented methods is something you can only do in Objective-C. Apple has [documentation](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift) on Obj-C / Swift interoperability. I hope this helps!

**Comment by L1cardo** [comment]
I really have no idea about what to do . :(
I think that importing an OC file to Swift requires a `.m` file , but there is only `TouchBar.h`, so I don't know which file to import and what to do after importing.
Could you please make it a little clear ?

**Comment by a2** [comment]
This is all in the documentation, but you'll want to create and set up a "`YourTarget`-Bridging-Header.h" file and add `#import "TouchBar.h"` to it.

**Comment by L1cardo** [comment]
Which file in your project should I copy to my project?

> This is all in the documentation, but you'll want to create and set up a "`YourTarget`-Bridging-Header.h" file and add `#import "TouchBar.h"` to it.

I have done that already. 
Which file in your project should I copy to my project? All of them or just  `TouchBar.h`

**Comment by a2** [comment]
`TouchBar.h` should suffice. Don't forget to configure the Swift Bridging Header in your project's Build Settings.

<img width="193" alt="image" src="https://user-images.githubusercontent.com/241156/68070658-ef04b500-fd68-11e9-978c-6042cec26765.png">

**Comment by L1cardo** [comment]
thanks!
I will see what I can do !
Thanks again!

**Comment by L1cardo** [comment]
I have imported the file and I can use the func such as `addSystemTrayItem`, but it is really difficult for me to display an item on the touchbar.
1. I dont know how to add an item on touchbar
2. I am getting this error
![image](https://user-images.githubusercontent.com/33802186/68071140-74f91e00-fdb2-11e9-9ebc-383526fc9bf8.png)

**Comment by L1cardo** [comment]
This is what I did
![image](https://user-images.githubusercontent.com/33802186/68071467-a32c2d00-fdb5-11e9-986f-90ffca09376f.png)

**Comment by a2** [comment]
It's also possible that the symbol has been removed in macOS Catalina, if that's what you're using. I haven't tried it recently.

**Comment by L1cardo** [comment]
I can build and run your project, but not mine

**Comment by a2** [comment]
Did you link against `DFRFoundation.framework`?

**Comment by L1cardo** [comment]
Ooooooop! 
I just found that !!!
Now I win!!
Thanks for tonight's helping!!!
